import os
import math
from datetime import datetime

# 1. FORCE L'APERCU SMARTPHONE (A mettre TOUT EN HAUT du code)
from kivy.config import Config
Config.set('graphics', 'width', '360')
Config.set('graphics', 'height', '740')
Config.set('graphics', 'resizable', False)

# Sécurité pour l'affichage graphique sur votre écran
os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2' 

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
# ... (le reste de votre code ne change pas)